{% set version = "1.2.4" %}

package:
  name: robometry-split
  version: {{ version }}

source:
  - url: https://github.com/robotology/robometry/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 18803a79893fdb88eec15ca2ae67931bf16edcf612d429c1e7877a5e908ca51e

build:
  number: 1

outputs:
  - name: librobometry
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("librobometry", max_pin='x.x.x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
      host:
        - ycm-cmake-modules
        - libmatio-cpp
        - libboost-devel
        - nlohmann_json
        - libyarp
      run:
        - libboost-headers

    test:
      commands:
        - test -f $PREFIX/include/robometry/BufferManager.h  # [unix]
        - test -f $PREFIX/lib/librobometry${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_INC%\\robometry\\BufferManager.h exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\robometry.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\robometry.dll exit 1  # [win]
        - python -m pip install git+https://github.com/ami-iit/cmake-package-check@v0.0.1
        - cmake-package-check robometry
      requires:
        - python
        - pip
        - jinja2
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        - git

  - name: robometry
    build:
      run_exports:
        - {{ pin_subpackage("librobometry", max_pin='x') }}
    requirements:
      run:
        - {{ pin_subpackage("librobometry", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/include/robometry/BufferManager.h  # [unix]
        - test -f $PREFIX/lib/librobometry${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_INC%\\robometry\\BufferManager.h exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\robometry.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\robometry.dll exit 1  # [win]

about:
  home: https://github.com/robotology/robometry
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Telemetry library for logging data.

extra:
  recipe-maintainers:
    - traversaro
